### ISSUE TITLE
ROC curve for logistic regression

### ISSUE THREAD

**Issue by mzakariaCERN** [eulerfan/Russian_twitter_trolls#10]

**Comment by eulerfan** [comment]
Having trouble getting the AUC to work properly. 
Error in .performance.auc(fpr.stop = 1, predictions = c(0.988080784098487,  : 
  Not enough distinct predictions to compute area under the ROC curve.
> checked all google listing

**Comment by mzakariaCERN** [comment]
I think this could be the issue:

https://stackoverflow.com/a/25685296/4656963

**Comment by eulerfan** [comment]
I eventually went to a basic roc() function to create the ROC and auc.
