### ISSUE TITLE
Try making Random Forest (also addd ROC for that) 

### ISSUE THREAD

**Issue by mzakariaCERN** [eulerfan/Russian_twitter_trolls#11]

**Comment by eulerfan** [comment]
The code seems fine, but the numbers are wrong.  Right now my dependent variable is r_nr, should run two different models with dependent variable r in one model and nr in the other model ?

**Comment by mzakariaCERN** [comment]
I don't think so. If you created a random mix of r_nr and r in the same table (with one column indicating is that tweet was r or r_nr) and feed it to the algorithm

**Comment by eulerfan** [comment]
The numbers did clear up after the for decision tree and the random forest after the logistic regression problem was solved. There was a variable issue in the split of the sparse matrix.
