### ISSUE TITLE
Tidying up the document 

### ISSUE THREAD

**Issue by mzakariaCERN** [eulerfan/Russian_twitter_trolls#4]
Line 6 please add a link to the resource you describe. 
https://github.com/eulerfan/Russian_twitter_trolls/blob/master/russian_trolls.md

example [GitHub](http://github.com)

So put the title to click on between [] 
and the actual link in () 
[title](link)

**Comment by eulerfan** [comment]
[here is ccn](www.cnn.com)

**Comment by eulerfan** [comment]
It was changed. I like this tool.
