### ISSUE TITLE
Line 173 investigate the different levels

### ISSUE THREAD

**Issue by mzakariaCERN** [eulerfan/Russian_twitter_trolls#7]
When you join the tables there is a warning that you are joining factors with different levels. Can you run str(file) so we can see what levels they each have. This is to make sure we are not losing any data levels.

**Comment by eulerfan** [comment]
The should not be joined horizontally. They should be combined vertically. Use adding row command.

**Comment by mzakariaCERN** [comment]
total <- rbind(data frameA, data frameB)  [provided the two tables have the same structure]

**Comment by eulerfan** [comment]
I combined the data correctly, but the numbers did not change very much. It is much cleaner.
