### ISSUE TITLE
In the logistic regression, we need a count on the number of rows after the split

### ISSUE THREAD

**Issue by mzakariaCERN** [eulerfan/Russian_twitter_trolls#9]
we need to count how many rows we have after the split to try and trace back the issue of having the full data in your confusion matrix

**Comment by eulerfan** [comment]
pending resolving issue #7

**Comment by eulerfan** [comment]
The issue with combining data frames did not solve the issue. I went the every line of the logistic chunk of the code and found the wrong sign. "greater than"  not "less than". It is now fixed.
